#!/bin/bash

# serveranary - Daemonize the server canary
#
# chkconfig: - 85 15
# description: Daemonize the server canary
# processname: canary
# config: /etc/default/canary
# pidfile: /var/run/canary.pid
#
### BEGIN INIT INFO
# Provides: skedify
# Required-Start $local_fs $remote_fs $network
# Required-Stop $local_fs $remote_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop the server canary
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

#PATH=/sbin:/bin:/usr/sbin:/usr/bin

NAME="root"
OWNER="root"
DESC="python servercanary.py"
DAEMON="python servercanary.py"
PIDFILE="/var/run/servercanary.pid"
LOCKFILE="/var/lock/servercanary.lock"

DAEMON_OPTS=""

cd ~

start() {
    if [ ! -f $PIDFILE ]; then
      echo -n "Starting $DESC: "
      daemon --pidfile=$PIDFILE --user=$OWNER $DAEMON $DAEMON_OPTS
      RETVAL=$?
      echo
      sleep 1
      [ $RETVAL = 0 ] && touch $LOCKFILE
      return $RETVAL
    fi
}

stop() {
    echo -n $"Stopping $DESC: "
    killproc ${DESC}
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${LOCKFILE} ${PIDFILE}
}

reload() {
    echo -n $"Reloading $DESC: "
    killproc -p ${PIDFILE} ${DESC} -HUP
    RETVAL=$?
    echo
}
rh_status() {
    status -p ${PIDFILE} ${DAEMON}
}

case "$1" in
    start)
        rh_status >/dev/null 2>&1 && exit 0
        start
        ;;
    stop)
        stop
        ;;
    status)
        rh_status
        RETVAL=$?
        ;;
    restart)
        stop
        start
        ;;
    reload)
        reload
        ;;
    *)
        echo $"Usage: $NAME {start|stop|restart|reload|status|help}"
        RETVAL=2
esac

exit $RETVAL
